# Generated by Django 5.2.5 on 2025-08-13 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر محصول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedCloth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='برند لباس')),
                ('size', models.CharField(max_length=50, verbose_name='سایز')),
                ('issues', models.TextField(blank=True, null=True, verbose_name='پارگی یا خوردگی')),
                ('full_photo', models.ImageField(upload_to='clothes/full/', verbose_name='عکس کلی')),
                ('fabric_photo', models.ImageField(upload_to='clothes/fabric/', verbose_name='عکس پارچه')),
                ('brand_photo', models.ImageField(blank=True, null=True, upload_to='clothes/brand/', verbose_name='عکس برند')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'لباس ارسال شده',
                'verbose_name_plural': 'لباس\u200cهای ارسال شده',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
