# Generated by Django 5.2.5 on 2025-08-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='داستان لباس'),
        ),
    ]
