# Generated by Django 5.2.5 on 2025-08-16 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='کد عمومی (برای لینک/QR)'),
        ),
    ]
